language: python
python:
  - "2.7"
env:
  - SUBLIME_TEXT_VERSION="2"
  - SUBLIME_TEXT_VERSION="3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y diction
  - diction --version

install:
  # Install Sublime Text and output version
  - curl https://raw.github.com/twolfson/sublime-installer/0.1.3/install.sh | sh -s $SUBLIME_TEXT_VERSION
  - subl --version

  # Install dev dependencies
  - pip install sublime-plugin-tests

  # Install our plugin
  - mkdir -p '~/.config/sublime-text-'$SUBLIME_TEXT_VERSION'/Packages/'
  - ln -s $PWD '~/.config/sublime-text-'$SUBLIME_TEXT_VERSION'/Packages/Diction'

before_script:
  # Generate a screen buffer to collect Sublime Text window
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Ensure the scripts self-terminate
  - export SUBLIME_AUTO_KILL=TRUE

script:
  # Run our tests
  - nosetests --nocapture --verbose --stop
